// const getAvatarImage = (id) => `https://robohash.org/${id}.png`;

const getAvatarImage = (id, gender = 'male') => {
 const r = `https://avatars.dicebear.com/api/big-ears/${id}.svg?skinColor=variant02`;
 // ${gender =='female'?'&hair=straightHair':''}`;
 return r;
}

export const Users = {
  ivanv: { id: "1", name: "Иван", username: "ivanv", image: getAvatarImage('ivanv') },
  milanr: { id: "2", name: "Милан", username: "milanr", image: getAvatarImage('milanr') },
  lazarp: { id: "3", name: "Лазар", username: "lazarp", image: getAvatarImage('lazarp') },
  mimiz: { id: "4", name: "Мими", username: "mimiz", image: getAvatarImage('mimiz', 'female') },
  mirak: { id: "5", name: "Мира", username: "mirak", image: getAvatarImage('mirak', 'female') },
  smiljandj: { id: "6", name: "Смиљан", username: "smiljandj", image: getAvatarImage('smiljandj') },
  janam: { id: "7", name: "Јана", username: "janam", image: getAvatarImage('janam', 'female') },
  igorj: { id: "8", name: "Игор", username: "igorj", image: getAvatarImage('igorj') },
  tijanat: { id: "9", name: "Тијана", username: "tijant", image: getAvatarImage('tijanat', 'female') },
  draganat: { id: "10", name: "Драгана", username: "draganat", image: getAvatarImage('draganat', 'female') },
  darkos: { id: "11", name: "Дарко", username: "darkos", image: getAvatarImage('darkos') },
  bojans: { id: "12", name: "Бојан", username: "bojans", image: getAvatarImage('bojans') },
};
export const data = {
    id: '1',
    name: 'Ласер таг',
    organization: 'LaserWar',
    location: 'Каменички парк',
    date: '05.10.2022.',
    participants: [
        Users.ivanv, Users.milanr, Users.lazarp, Users.mimiz, Users.mirak, Users.smiljandj, Users.janam, Users.igorj, Users.tijanat, Users.draganat, Users.darkos, Users.bojans
    ],
    teams: [
      {
        id: '1',
        name: 'Red',
        participants: [
          Users.ivanv,
          Users.milanr,
          Users.lazarp,
          Users.mimiz,
          Users.mirak,
          Users.smiljandj,
        ]
      },
      {
        id: '2',
        name: 'Blue',
        participants: [
          Users.janam,
          Users.igorj,
          Users.tijanat,
          Users.draganat,
          Users.darkos,
          Users.bojans,
        ]
      },
    ],
    statistic: [
        {
          user: Users.ivanv,
          teamId: '1',
          rating: 22.85,
          kills: 12,
          accuracy: 7.41,
          shotFired: 581,
          hits: {
            total: 43,
            data: [
              { target: Users.igorj, count: 6 },
              { target: Users.tijanat, count: 2 },
              { target: Users.draganat, count: 10 },
              { target: Users.darkos, count: 5 },
              { target: Users.janam, count: 13 },
              { target: Users.bojans, count: 7 },
            ],
          },
          wounds: {
            total: 71,
            data: [
              { target: Users.bojans, count: 18 },
              { target: Users.igorj, count: 9 },
              { target: Users.janam, count: 12 },
              { target: Users.tijanat, count: 14 },
              { target: Users.draganat, count: 7 },
              { target: Users.darkos, count: 11 },
            ],
          },
          damagePerShot: 35,
          damageDone: 1505,
          gameOver: 24,
          damageGet: 2485,
          medicine: 12,
          ammoBoxes: 2,
          gameTime: "19:42:41",
        },

        {
          user: Users.milanr,
          teamId: '1',
          rating: 55.82,
          kills: 32,
          accuracy: 8.24,
          shotFired: 1116,
          hits: {
            total: 92,
            data: [
              { target: Users.igorj, count: 10 },
              { target: Users.tijanat, count: 26 },
              { target: Users.draganat, count: 7 },
              { target: Users.darkos, count: 31 },
              { target: Users.janam, count: 10 },
              { target: Users.bojans, count: 8 },
            ],
          },
          wounds: {
            total: 63,
            data: [
              { target: Users.bojans, count: 9 },
              { target: Users.igorj, count: 13 },
              { target: Users.janam, count: 11 },
              { target: Users.tijanat, count: 13 },
              { target: Users.draganat, count: 1 },
              { target: Users.darkos, count: 16 },
            ],
          },
          damagePerShot: 35,
          damageDone: 3220,
          gameOver: 22,
          damageGet: 2205,
          medicine: 20,
          ammoBoxes: 1,
          gameTime: "19:21:00",
        },

        {
          user: Users.lazarp,
          teamId: '1',
          rating: 53.28,
          kills: 30,
          accuracy: 10.14,
          shotFired: 996,
          hits: {
            total: 101,
            data: [
              { target: Users.igorj, count: 10 },
              { target: Users.tijanat, count: 29 },
              { target: Users.draganat, count: 24 },
              { target: Users.darkos, count: 25 },
              { target: Users.janam, count: 7 },
              { target: Users.bojans, count: 6 },
            ],
          },
          wounds: {
            total: 75,
            data: [
              { target: Users.bojans, count: 19 },
              { target: Users.igorj, count: 16 },
              { target: Users.janam, count: 9 },
              { target: Users.tijanat, count: 11 },
              { target: Users.draganat, count: 10 },
              { target: Users.darkos, count: 10 },
            ],
          },
          damagePerShot: 35,
          damageDone: 3535,
          gameOver: 20,
          damageGet: 2625,
          medicine: 6,
          ammoBoxes: 0,
          gameTime: "19:46:50",
        },

        {
          user: Users.mimiz,
          teamId: '1',
          rating: 28.53,
          kills: 15,
          accuracy: 5.87,
          shotFired: 613,
          hits: {
            total: 36,
            data: [
              { target: Users.igorj, count: 7 },
              { target: Users.tijanat, count: 0 },
              { target: Users.draganat, count: 4 },
              { target: Users.darkos, count: 13 },
              { target: Users.janam, count: 5 },
              { target: Users.bojans, count: 7 },
            ],
          },
          wounds: {
            total: 46,
            data: [
              { target: Users.bojans, count: 22 },
              { target: Users.igorj, count: 10 },
              { target: Users.janam, count: 7 },
              { target: Users.tijanat, count: 4 },
              { target: Users.draganat, count: 0 },
              { target: Users.darkos, count: 3 },
            ],
          },
          damagePerShot: 35,
          damageDone: 1260,
          gameOver: 17,
          damageGet: 1610,
          medicine: 8,
          ammoBoxes: 1,
          gameTime: "19:48:25",
        },

        {
          user: Users.mirak,
          teamId: '1',
          rating: 36.51,
          kills: 14,
          accuracy: 3.80,
          shotFired: 1500,
          hits: {
            total: 57,
            data: [
              { target: Users.igorj, count: 10 },
              { target: Users.tijanat, count: 13 },
              { target: Users.draganat, count: 10 },
              { target: Users.darkos, count: 8 },
              { target: Users.janam, count: 4 },
              { target: Users.bojans, count: 12 },
            ],
          },
          wounds: {
            total: 55,
            data: [
              { target: Users.bojans, count: 18 },
              { target: Users.igorj, count: 10 },
              { target: Users.janam, count: 3 },
              { target: Users.tijanat, count: 11 },
              { target: Users.draganat, count: 5 },
              { target: Users.darkos, count: 8 },
            ],
          },
          damagePerShot: 35,
          damageDone: 1995,
          gameOver: 19,
          damageGet: 1925,
          medicine: 16,
          ammoBoxes: 0,
          gameTime: "19:48:17",
        },

        {
          user: Users.smiljandj,
          teamId: '1',
          rating: 41.18,
          kills: 29,
          accuracy: 9.34,
          shotFired: 814,
          hits: {
            total: 76,
            data: [
              { target: Users.igorj, count: 10 },
              { target: Users.tijanat, count: 8 },
              { target: Users.draganat, count: 16 },
              { target: Users.darkos, count: 17 },
              { target: Users.janam, count: 16 },
              { target: Users.bojans, count: 9 },
            ],
          },
          wounds: {
            total: 72,
            data: [
              { target: Users.bojans, count: 9 },
              { target: Users.igorj, count: 22 },
              { target: Users.janam, count: 17 },
              { target: Users.tijanat, count: 9 },
              { target: Users.draganat, count: 6 },
              { target: Users.darkos, count: 9 },
            ],
          },
          damagePerShot: 35,
          damageDone: 2660,
          gameOver: 25,
          damageGet: 2520,
          medicine: 13,
          ammoBoxes: 1,
          gameTime: "19:05:28",
        },
        {
          user: Users.janam,
          teamId: '2',
          rating: 39.37,
          kills: 23,
          accuracy: 6.06,
          shotFired: 974,
          hits: {
            total: 59,
            data: [
              { target: Users.milanr, count: 11 },
              { target: Users.lazarp, count: 9 },
              { target: Users.ivanv, count: 12 },
              { target: Users.mimiz, count: 7 },
              { target: Users.mirak, count: 3 },
              { target: Users.smiljandj, count: 17 },
            ],
          },
          wounds: {
            total: 55,
            data: [
              { target: Users.ivanv, count: 13 },
              { target: Users.lazarp, count: 7 },
              { target: Users.mimiz, count: 5 },
              { target: Users.mirak, count: 4 },
              { target: Users.smiljandj, count: 16 },
              { target: Users.milanr, count: 10 },
            ],
          },
          damagePerShot: 35,
          damageDone: 2065,
          gameOver: 18,
          damageGet: 1925,
          medicine: 6,
          ammoBoxes: 0,
          gameTime: "18:52:01",
        },

        {
          user: Users.igorj,
          teamId: '2',
          rating: 65.81,
          kills: 27,
          accuracy: 16.63,
          shotFired: 481,
          hits: {
            total: 80,
            data: [
              { target: Users.milanr, count: 13 },
              { target: Users.lazarp, count: 16 },
              { target: Users.ivanv, count: 9 },
              { target: Users.mimiz, count: 10 },
              { target: Users.mirak, count: 10 },
              { target: Users.smiljandj, count: 22 },
            ],
          },
          wounds: {
            total: 53,
            data: [
              { target: Users.ivanv, count: 6 },
              { target: Users.lazarp, count: 10 },
              { target: Users.mimiz, count: 10 },
              { target: Users.mirak, count: 10 },
              { target: Users.smiljandj, count: 10 },
              { target: Users.milanr, count: 7 },
            ],
          },
          damagePerShot: 35,
          damageDone: 2800,
          gameOver: 18,
          damageGet: 1855,
          medicine: 8,
          ammoBoxes: 0,
          gameTime: "18:45:20",
        },

        {
          user: Users.tijanat,
          teamId: '2',
          rating: 30.06,
          kills: 21,
          accuracy: 7.45,
          shotFired: 832,
          hits: {
            total: 62,
            data: [
              { target: Users.milanr, count: 13 },
              { target: Users.lazarp, count: 11 },
              { target: Users.ivanv, count: 14 },
              { target: Users.mimiz, count: 4 },
              { target: Users.mirak, count: 11 },
              { target: Users.smiljandj, count: 9 },
            ],
          },
          wounds: {
            total: 78,
            data: [
              { target: Users.ivanv, count: 2 },
              { target: Users.lazarp, count: 29 },
              { target: Users.mimiz, count: 0 },
              { target: Users.mirak, count: 13 },
              { target: Users.smiljandj, count: 8 },
              { target: Users.milanr, count: 26 },
            ],
          },
          damagePerShot: 35,
          damageDone: 2170,
          gameOver: 27,
          damageGet: 2730,
          medicine: 15,
          ammoBoxes: 1,
          gameTime: "02:10:31",
        },

        {
          user: Users.draganat,
          teamId: '2',
          rating: 14.73,
          kills: 11,
          accuracy: 4.87,
          shotFired: 596,
          hits: {
            total: 29,
            data: [
              { target: Users.milanr, count: 1 },
              { target: Users.lazarp, count: 10 },
              { target: Users.ivanv, count: 7 },
              { target: Users.mimiz, count: 0 },
              { target: Users.mirak, count: 5 },
              { target: Users.smiljandj, count: 6 },
            ],
          },
          wounds: {
            total: 71,
            data: [
              { target: Users.ivanv, count: 10 },
              { target: Users.lazarp, count: 24 },
              { target: Users.mimiz, count: 4 },
              { target: Users.mirak, count: 10 },
              { target: Users.smiljandj, count: 16 },
              { target: Users.milanr, count: 7 },
            ],
          },
          damagePerShot: 35,
          damageDone: 1015,
          gameOver: 23,
          damageGet: 2485,
          medicine: 18,
          ammoBoxes: 0,
          gameTime: "18:49:03",
        },

        {
          user: Users.darkos,
          teamId: '2',
          rating: 24.17,
          kills: 21,
          accuracy: 13.60,
          shotFired: 419,
          hits: {
            total: 57,
            data: [
              { target: Users.milanr, count: 16 },
              { target: Users.lazarp, count: 10 },
              { target: Users.ivanv, count: 11 },
              { target: Users.mimiz, count: 3 },
              { target: Users.mirak, count: 8 },
              { target: Users.smiljandj, count: 9 },
            ],
          },
          wounds: {
            total: 99,
            data: [
              { target: Users.ivanv, count: 5 },
              { target: Users.lazarp, count: 25 },
              { target: Users.mimiz, count: 13 },
              { target: Users.mirak, count: 8 },
              { target: Users.smiljandj, count: 17 },
              { target: Users.milanr, count: 31 },
            ],
          },
          damagePerShot: 35,
          damageDone: 1995,
          gameOver: 30,
          damageGet: 3465,
          medicine: 2,
          ammoBoxes: 0,
          gameTime: "18:47:50",
        },
        {
          user: Users.bojans,
          teamId: '2',
          rating: 80.90,
          kills: 22,
          accuracy: 13.87,
          shotFired: 685,
          hits: {
            total: 95,
            data: [
              { target: Users.milanr, count: 9 },
              { target: Users.lazarp, count: 19 },
              { target: Users.ivanv, count: 18 },
              { target: Users.mimiz, count: 22 },
              { target: Users.mirak, count: 18 },
              { target: Users.smiljandj, count: 9 },
            ],
          },
          wounds: {
            total: 49,
            data: [
              { target: Users.ivanv, count: 7 },
              { target: Users.lazarp, count: 6 },
              { target: Users.mimiz, count: 7 },
              { target: Users.mirak, count: 12 },
              { target: Users.smiljandj, count: 9 },
              { target: Users.milanr, count: 8 },
            ],
          },
          damagePerShot: 35,
          damageDone: 3325,
          gameOver: 17,
          damageGet: 1715,
          medicine: 17,
          ammoBoxes: 0,
          gameTime: "18:54:26",
        },
      ]
};


export const games = [
  data
]